# docker-compose.yaml
services:
  wa-gateway:
    container_name: "wa-gateway"
    restart: unless-stopped
    image: mimamch/wa-gateway:latest
    volumes:
      - ./wa_credentials:/app/wa_credentials
      - ./media:/app/media
    ports:
      - "5001:5001"
    environment:
      - KEY=secret # optional, make your own api key
      - WEBHOOK_BASE_URL="https://fammey88.konek.web.id/mima.php" # optional, if you need webhook
      - REDIS_URL= # optional, if you want store session to redis instead of local files
